import Shit from './shit';
import AddType from './add-type';
import AddSalary from './add-salary';
import AddEmp from './add-emp';

export default class Account extends Shit {
	constructor() {
		super();
		this.OpenDate = new Date();
		this.AccountPerm = new Array<any>();
		this.AccountSheet = new Array<any>();
		this.Bank = new Array<any>();
		this.ConTypeAddTaxAccountNavigation = new Array<Account>();
		this.ConTypeCustomerAccountNavigation = new Array<AddType>();
		this.ConTypeDiscountAccountNavigation = new Array<AddSalary>();
		this.ConTypeMonyAccountNavigation = new Array<AddEmp>();
		this.ConTypeProcessExpenceNavigation = new Array<any>();
		this.ConTypeProductAccountNavigation = new Array<any>();
		this.ConTypeSalesAccountNavigation = new Array<any>();
		this.ConTypeShipmentAccountNavigation = new Array<any>();
		this.ConTypeShipmentCostAcNavigation = new Array<any>();
		this.ConTypeShipmentRevenueAcNavigation = new Array<any>();
		this.ConTypeTaxAccountNavigation = new Array<any>();
		this.Contract = new Array<any>();
		this.CustomerAccount = new Array<any>();
		this.EntriesDetails = new Array<any>();
		this.ExpencesType = new Array<any>();
		this.GroupExpncesAccountNavigation = new Array<any>();
		this.GroupInsuranceAccountNavigation = new Array<any>();
		this.GroupInsuranceCashAccountNavigation = new Array<any>();
		this.GroupMonyAccontNavigation = new Array<any>();
		this.GroupTaxAccountNavigation = new Array<any>();
		this.GroupexpectExpencesAcountNavigation = new Array<any>();
		this.GrouploansAccountNavigation = new Array<any>();
		this.InstalSetupAccount = new Array<any>();
		this.InstalSetupAccountSecondNavigation = new Array<any>();
		this.InverseAcParentNavigation = new Array<Account>();
		this.InvoiceTypeEndAccountNavigation = new Array<any>();
		this.InvoiceTypeProductAccountNavigation = new Array<any>();
		this.JobSheet = new Array<any>();
		this.JobSheetType = new Array<any>();
		this.Loans = new Array<any>();
		this.MachinWorkDetails = new Array<any>();
		this.MachinWorkSettingDiscountAccountNavigation = new Array<any>();
		this.MachinWorkSettingProcessAccountNavigation = new Array<any>();
		this.MachinWorkSettingSupplierAccountNavigation = new Array<any>();
		this.PaymentMethod = new Array<any>();
		this.PaymentRecive = new Array<any>();
		this.PointOfSale = new Array<any>();
		this.ProProcessType = new Array<any>();
		this.ProcessAcount = new Array<any>();
		this.PurchaseSettingDiscountAccountNavigation = new Array<any>();
		this.PurchaseSettingPurchaseAccountNavigation = new Array<any>();
		this.PurchaseSettingSupplierAccountNavigation = new Array<any>();
		this.PurchaseSettingmonyAccountNavigation = new Array<any>();
		this.SalesExpencesType = new Array<any>();
		this.SalesTupeAddExpencesAccountNavigation = new Array<any>();
		this.SalesTupeExpencesAccountNavigation = new Array<any>();
		this.SalesTupeTaxAccountNavigation = new Array<any>();
		this.SalesTupeTupeCostItemNavigation = new Array<any>();
		this.ShipmentOrderDetials = new Array<any>();
		this.StoreCapitalAccountNavigation = new Array<any>();
		this.StoreCustomerAccountNavigation = new Array<any>();
		this.StoreMonyaccountNavigation = new Array<any>();
		this.StoreStoreAccountNavigation = new Array<any>();
		this.Supplier = new Array<any>();
	}

	public AcID: number;
	public AcName: string;
	public AcCode: number;
	public CreditORDepit: boolean;
	public AllORDetail: boolean;
	public ISCost: boolean;
	public AcParent: number;
	public ComID: number;
	public AcType: number;
	public Sheet: number;
	public CostID: number;
	public AcIndex: number;
	public OpenDate: Date;
	public OpenIsDepit: boolean;
	public OpenAccount: number;
	public Setting: number;
	public DisplayCurrancy: number;
	public AcParentNavigation: Account;
	public AcTypeNavigation: any;
	public Com: any;
	public Cost: any;
	public DisplayCurrancyNavigation: any;
	public SettingNavigation: any;
	public SheetNavigation: any;
	public AccountPerm: Array<any>;
	public AccountSheet: Array<any>;
	public Bank: Array<any>;
	public ConTypeAddTaxAccountNavigation: Array<Account>;
	public ConTypeCustomerAccountNavigation: Array<AddType>;
	public ConTypeDiscountAccountNavigation: Array<AddSalary>;
	public ConTypeMonyAccountNavigation: Array<AddEmp>;
	public ConTypeProcessExpenceNavigation: Array<any>;
	public ConTypeProductAccountNavigation: Array<any>;
	public ConTypeSalesAccountNavigation: Array<any>;
	public ConTypeShipmentAccountNavigation: Array<any>;
	public ConTypeShipmentCostAcNavigation: Array<any>;
	public ConTypeShipmentRevenueAcNavigation: Array<any>;
	public ConTypeTaxAccountNavigation: Array<any>;
	public Contract: Array<any>;
	public CustomerAccount: Array<any>;
	public EntriesDetails: Array<any>;
	public ExpencesType: Array<any>;
	public GroupExpncesAccountNavigation: Array<any>;
	public GroupInsuranceAccountNavigation: Array<any>;
	public GroupInsuranceCashAccountNavigation: Array<any>;
	public GroupMonyAccontNavigation: Array<any>;
	public GroupTaxAccountNavigation: Array<any>;
	public GroupexpectExpencesAcountNavigation: Array<any>;
	public GrouploansAccountNavigation: Array<any>;
	public InstalSetupAccount: Array<any>;
	public InstalSetupAccountSecondNavigation: Array<any>;
	public InverseAcParentNavigation: Array<Account>;
	public InvoiceTypeEndAccountNavigation: Array<any>;
	public InvoiceTypeProductAccountNavigation: Array<any>;
	public JobSheet: Array<any>;
	public JobSheetType: Array<any>;
	public Loans: Array<any>;
	public MachinWorkDetails: Array<any>;
	public MachinWorkSettingDiscountAccountNavigation: Array<any>;
	public MachinWorkSettingProcessAccountNavigation: Array<any>;
	public MachinWorkSettingSupplierAccountNavigation: Array<any>;
	public PaymentMethod: Array<any>;
	public PaymentRecive: Array<any>;
	public PointOfSale: Array<any>;
	public ProProcessType: Array<any>;
	public ProcessAcount: Array<any>;
	public PurchaseSettingDiscountAccountNavigation: Array<any>;
	public PurchaseSettingPurchaseAccountNavigation: Array<any>;
	public PurchaseSettingSupplierAccountNavigation: Array<any>;
	public PurchaseSettingmonyAccountNavigation: Array<any>;
	public SalesExpencesType: Array<any>;
	public SalesTupeAddExpencesAccountNavigation: Array<any>;
	public SalesTupeExpencesAccountNavigation: Array<any>;
	public SalesTupeTaxAccountNavigation: Array<any>;
	public SalesTupeTupeCostItemNavigation: Array<any>;
	public ShipmentOrderDetials: Array<any>;
	public StoreCapitalAccountNavigation: Array<any>;
	public StoreCustomerAccountNavigation: Array<any>;
	public StoreMonyaccountNavigation: Array<any>;
	public StoreStoreAccountNavigation: Array<any>;
	public Supplier: Array<any>;
}
